server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  types {
    application/manifest+json webmanifest;
    application/javascript js;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
